project:
  title: "Etudes"
  execute-dir: project
  type: website

# Default knitr options
execute:
  cache: true
  echo: true
  message: true
  warning: true
  collapse: true
  comment: "#>"

format:
  html:
    theme: 
      dark: [cosmo, theme-dark.scss]
      light: cosmo
    css: styles.css
    toc: true
    toc-location: left
    page-navigation: true
    repo-url: https://github.com/venpopov/etudes
    repo-actions: [edit, issue]
    highlight-style: monokai

author:
  - name: Vencislav Popov
    url: https://venpopov.com
    orcid: 0000-0002-8073-4199

# Enable banner style title blocks
title-block-banner: "#eeeeee"
